# worktree_ios_dev_tool/src/worktree_ios_dev_tool/bootstrap.py
"""Implementation of the ``proj init`` verb.

The module name is historical (predates the ``proj`` namespace); the public
entry point is :func:`run`, which is invoked from
:mod:`worktree_ios_dev_tool.proj.cmd_init`.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from . import ui
from .errors import UserError
from .paths import find_worktree_root_for_bootstrap

_GITIGNORE_MARKER = "# added by worktree-ios-dev-tool proj init"
_GITIGNORE_ENTRY = "worktree-ios-dev/"


def find_xcodeprojs(root: Path) -> list[Path]:
    """Find all *.xcodeproj directories under root, sorted. Does not recurse inside .xcodeproj."""
    results = []
    for p in sorted(root.rglob("*.xcodeproj")):
        rel_parts = p.relative_to(root).parts[:-1]
        if not any(part.endswith(".xcodeproj") for part in rel_parts):
            results.append(p)
    return results


def fetch_schemes(xcodeproj: Path) -> list[str]:
    """Return scheme names from xcodebuild -list -json. Returns [] on failure."""
    try:
        result = subprocess.run(
            ["xcodebuild", "-list", "-project", str(xcodeproj), "-json"],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    if result.returncode != 0:
        return []
    try:
        data = json.loads(result.stdout)
        return data.get("project", {}).get("schemes", [])
    except (json.JSONDecodeError, AttributeError):
        return []


def detect_packages_root(xcodeproj: Path) -> Path | None:
    """Return <xcodeproj_dir>/Packages if it exists, else None."""
    candidate = xcodeproj.parent / "Packages"
    return candidate if candidate.is_dir() else None


def _pick_one(label: str, options: list[str], yes: bool) -> str:
    """Return single option directly, prompt if TTY, error if non-interactive and ambiguous."""
    if len(options) == 1:
        return options[0]
    if yes or not sys.stdin.isatty() or not sys.stdout.isatty():
        lines = "\n".join(f"  {o}" for o in options)
        raise UserError(
            f"Multiple {label} found. Pass the appropriate flag:\n{lines}"
        )
    try:
        from InquirerPy import inquirer
        return inquirer.fuzzy(message=f"Select {label}:", choices=options).execute()
    except (ImportError, OSError, EOFError):
        print(f"Select {label}:")
        for i, opt in enumerate(options, start=1):
            print(f"  {i}. {opt}")
        while True:
            raw = input("Choice: ").strip()
            if raw.isdigit():
                idx = int(raw)
                if 1 <= idx <= len(options):
                    return options[idx - 1]
            print(f"Enter a number 1..{len(options)}.")


def _ensure_gitignored(root: Path) -> None:
    gi = root / ".gitignore"
    if gi.exists():
        content = gi.read_text()
        if any(line.strip() == _GITIGNORE_ENTRY for line in content.splitlines()):
            return
        suffix = "" if content.endswith("\n") else "\n"
        gi.write_text(content + f"{suffix}{_GITIGNORE_MARKER}\n{_GITIGNORE_ENTRY}\n")
    else:
        gi.write_text(f"{_GITIGNORE_MARKER}\n{_GITIGNORE_ENTRY}\n")


def _write_config(
    cfg_path: Path,
    xcodeproj: Path,
    root: Path,
    scheme: str,
    sim_prefix: str,
    pkg_root: Path | None,
) -> None:
    import tomlkit
    doc = tomlkit.document()
    doc.add(tomlkit.comment("worktree-ios-dev/project.toml"))
    doc.add(tomlkit.comment("Generated by `worktree-ios-dev-tool proj init`."))
    doc.add(tomlkit.comment("Edit as needed. Run `worktree-ios-dev-tool sim pick` to populate simulator.toml."))
    doc.add(tomlkit.nl())
    doc["schema_version"] = 1

    proj_table = tomlkit.table()
    proj_table.add("path", str(xcodeproj.relative_to(root)))
    proj_table.add("scheme", scheme)
    proj_table.add("configuration", "Debug")
    proj_table.add("simulator_prefix", sim_prefix)
    doc.add("project", proj_table)

    if pkg_root is not None:
        pkg_table = tomlkit.table()
        pkg_table.add("path", str(pkg_root.relative_to(root)))
        doc.add("packages_root", pkg_table)

    extras_table = tomlkit.table()
    extras_table.add("xcodebuild_flags", tomlkit.array())
    doc.add("extras", extras_table)

    cfg_path.write_text(tomlkit.dumps(doc))


def run(*, project: str | None, scheme: str | None, yes: bool, force: bool) -> int:
    root = find_worktree_root_for_bootstrap()
    pid = root / "worktree-ios-dev"
    cfg_path = pid / "project.toml"
    interactive = ui.is_interactive() and not yes

    if cfg_path.exists() and not force:
        ui.done(f"Already initialised at {pid} (use --force to re-seed).")
        return 0

    # ── Discover xcodeproj ──────────────────────────────────────────────────
    if project:
        xcodeproj = (root / project).resolve()
        if not xcodeproj.exists():
            raise UserError(f"Project not found: {xcodeproj}")
        try:
            xcodeproj.relative_to(root)
        except ValueError:
            raise UserError(
                f"--project path must be inside the worktree root ({root}). "
                f"Got: {xcodeproj}"
            )
        ui.step(f"Project: {project}")
    else:
        with ui.spinner("Scanning for Xcode projects..."):
            projs = find_xcodeprojs(root)

        if not projs:
            raise UserError("No *.xcodeproj found under the worktree root. Pass --project <path>.")

        rel_projs = [str(p.relative_to(root)) for p in projs]
        chosen_rel = _pick_one("project", rel_projs, yes)
        xcodeproj = (root / chosen_rel).resolve()
        ui.step(f"Project: {chosen_rel}")

    # ── Discover scheme ─────────────────────────────────────────────────────
    if scheme:
        chosen_scheme = scheme
        ui.step(f"Scheme: {chosen_scheme}")
    else:
        with ui.spinner("Fetching schemes..."):
            schemes = fetch_schemes(xcodeproj)

        if not schemes:
            raise UserError(f"No schemes found in {xcodeproj}. Pass --scheme <name>.")

        chosen_scheme = _pick_one("scheme", schemes, yes)
        ui.step(f"Scheme: {chosen_scheme}")

    # ── packages_root ───────────────────────────────────────────────────────
    pkg_root = detect_packages_root(xcodeproj)
    if pkg_root:
        ui.step(f"Packages root: {pkg_root.relative_to(root)}")

    # ── simulator_prefix ────────────────────────────────────────────────────
    sim_prefix = chosen_scheme
    if interactive:
        try:
            from InquirerPy import inquirer
            result = inquirer.text(
                message="Simulator prefix",
                default=chosen_scheme,
            ).execute()
            if result and result.strip():
                sim_prefix = result.strip()
        except (ImportError, OSError, EOFError):
            raw = input(f"Simulator prefix [{chosen_scheme}]: ").strip()
            if raw:
                sim_prefix = raw

    # ── Write ───────────────────────────────────────────────────────────────
    pid.mkdir(exist_ok=True)
    (pid / "derivedData").mkdir(exist_ok=True)
    _write_config(cfg_path, xcodeproj, root, chosen_scheme, sim_prefix, pkg_root)
    _ensure_gitignored(root)

    ui.sep()
    ui.done("worktree-ios-dev/project.toml written")
    ui.info(f"project          = {xcodeproj.relative_to(root)}")
    ui.info(f"scheme           = {chosen_scheme}")
    ui.info(f"simulator_prefix = {sim_prefix}")
    if pkg_root:
        ui.info(f"packages_root    = {pkg_root.relative_to(root)}")
    ui.sep()
    ui.done("Next: worktree-ios-dev-tool sim pick")

    return 0
